name: Translate and Upload README

on:
  push:
    paths:
      - 'README.md'

jobs:
  translate_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install command-line-args command-line-usage @vitalets/google-translate-api @octokit/rest

    - name: Translate to specified languages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }} # 使用 GitHub Token
      run: |
        node translate_readme.js 'README.md' \
          --ignore 1-3 \
          --from Chinese \
          --to en fr es
